version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
      - "9229:9229" # Для дебаггера, если используешь
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: nest_db
    # Основные настройки для Hot Reload:
    volumes:
      - .:/app               # Синхронизируем код
      - /app/node_modules    # Изолируем node_modules контейнера от локальных
    depends_on:
      - db

volumes:
  postgres_data: